### ISSUE TITLE
requests and xmltodict missing from requirements.txt

### ISSUE THREAD

**Issue by cnobile2012** [wellfire/hepdata-matchinggifts#3]
If tox is run the two missing imports seem to show up somehow, but if tests are run outside of tox the files are not there. It seems to me they need to be in the `requirements.txt` file.

**Comment by bennylope** [comment]
Thank you for reporting these issues. I'm going to try to get these updates into my schedule this week, if not pull requests welcome!

**Comment by bennylope** [comment]
Closed by aa4f7577cb11b583ae2643da84293cbac4494873
